// Libellé français (majuscules accentuées) du sous-type de question.
const LABELS: Record<string, string> = {
  capitale: 'CAPITALE',
  continent: 'CONTINENT',
  drapeau: 'DRAPEAU',
  fleuve: 'FLEUVE',
  frontiere: 'FRONTIÈRE',
  montagne: 'MONTAGNE',
  ocean: 'OCÉAN',
  superficie: 'SUPERFICIE',
  // histoire
  antiquite: 'ANTIQUITÉ',
  'moyen-age': 'MOYEN ÂGE',
  renaissance: 'RENAISSANCE',
  'xvii-xviii': 'XVIIᵉ-XVIIIᵉ',
  revolution: 'RÉVOLUTION',
  'empire-xix': 'XIXᵉ SIÈCLE',
  ww1: '14-18',
  'entre-deux-guerres': 'ENTRE-DEUX-GUERRES',
  ww2: '39-45',
  'guerre-froide': 'GUERRE FROIDE',
  contemporain: 'CONTEMPORAIN',
  // anglais CEDH
  foundations: 'FONDAMENTAUX',
  systems: 'LES DEUX SYSTÈMES',
  convention: 'LA CONVENTION',
  articles: 'QUEL ARTICLE ?',
  protocols: 'PROTOCOLES',
  'nature-of-rights': 'NATURE DES DROITS',
  principles: 'PRINCIPES',
  'protocol-1-1': 'P1 ART. 1 · PROPRIÉTÉ',
  'article-2': 'ART. 2 · VIE',
  'article-3': 'ART. 3 · TORTURE',
  'article-4': 'ART. 4 · ESCLAVAGE',
  'article-5': 'ART. 5 · LIBERTÉ',
  'article-6': 'ART. 6 · PROCÈS ÉQUITABLE',
  'article-7': 'ART. 7 · LÉGALITÉ',
  'article-8': 'ART. 8 · VIE PRIVÉE',
  'article-9': 'ART. 9 · CONSCIENCE',
  'article-10': 'ART. 10 · EXPRESSION',
  'article-11': 'ART. 11 · RÉUNION',
  'article-12': 'ART. 12 · MARIAGE',
  'article-13': 'ART. 13 · RECOURS',
  'article-14': 'ART. 14 · DISCRIMINATION',
  subsidiarity: 'SUBSIDIARITÉ',
  admissibility: 'RECEVABILITÉ',
  'time-limit': 'DÉLAI',
  filing: 'DÉPÔT',
  'interim-measures': 'MESURES PROVISOIRES',
  'just-satisfaction': 'SATISFACTION ÉQUITABLE',
  enforcement: 'EXÉCUTION',
  court: 'LA COUR',
  vocabulary: 'VOCABULAIRE',
  traps: 'PIÈGE',
  annales: 'ANNALES',
  // droit fiscal
  intro: 'INTRO · SOURCES',
  'ir-champ': 'IR · CHAMP',
  patrimoine: 'REVENUS DU PATRIMOINE',
  salaires: 'SALAIRES · DIRIGEANTS',
  'bic-principes': 'BIC · PRINCIPES',
  'bic-charges': 'BIC · CHARGES',
  'bic-plus-values': 'BIC · PLUS-VALUES',
  'bic-regimes': 'BIC · RÉGIMES · BNC',
  liquidation: 'LIQUIDATION DE L’IR',
  'tva-champ': 'TVA · CHAMP',
  'tva-territorialite': 'TVA · TERRITORIALITÉ',
  'tva-exigible': 'TVA · EXIGIBILITÉ · TAUX',
  'tva-deductible': 'TVA · DÉDUCTION',
}

export function subtypeLabel(subtype: string): string {
  const key = subtype.trim().toLowerCase()
  return LABELS[key] ?? subtype.toUpperCase()
}
